######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 21 23:45:33 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h snake.h
SOURCES += main.cpp mainwindow.cpp snake.cpp
